### ISSUE TITLE
Feature request: Additions to Home assistant auto discovery 

### ISSUE THREAD

**Issue by egeback** [remne/p1ib#1]
Hi

The home assistant MQTT auto discovery has the possibility to group multiple entries into devices for better mapping. Looking at the current implementation in p1ib it does not to expose this. The optional field is described here:
https://www.home-assistant.io/integrations/sensor.mqtt/#device. 

Also the availability tag could be good if data varies or the unit is closed down. Described here https://www.home-assistant.io/integrations/sensor.mqtt/#availability. (This probably needs that p1ib also needs a birth and will message to be added)

**Current exposed json:**
```
{
  "name": "p1ib_active_power_minus_l1",
  "stat_t": "homeassistant/sensor/p1ib/p1ib_active_power_m_l1/state",
  "device_class": "energy",
  "unit_of_measurement": "kW",
  "state_class": "measurement"
}

```
**example from zigbee2mqtt:**
```
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state"
    }
  ],
 "device": {
    "identifiers": [
      "zigbee2mqtt_0x84fd27fffe6e1d13"
    ],
    "manufacturer": "IKEA",
    "model": "TRADFRI ON/OFF switch (E1743)",
    "name": "....",
    "sw_version": "Zigbee2MQTT 1.21.2"
  },
...
}
zigbee2mqtt/bridge/state: online or offline
```

Regards, Marky

**Comment by remne** [comment]
Hi,
Yes, that is true I suppose. I'll look into it!
In the meantime there is a development firmware build you can try out (build b0524da in the p1ib firmware meny), if you want, which adds the device attribute.

Regards,
Andreas

**Comment by egeback** [comment]
Hi

Tested the development build and it looks like the device auto discover addition works as expected.. Thanks.

Regards, Marky

**Comment by remne** [comment]
Hi Marty,
The latest development firmware have the availability option enabled, if you wanna try it out!

Cheers,
Andreas

**Comment by egeback** [comment]
Hi Andreas,

I have tested the build and it works as expected. Tested a reboot and the state was changed.

<img width="594" alt="image" src="https://user-images.githubusercontent.com/3228822/153772093-cf57611e-1646-4c5f-9c2b-6f1602083aa1.png">

So from my perspective the request is fulfilled, but I guess you want to make a stable release to close the issue.

Best Regards, Marky

**Comment by remne** [comment]
Feature in release 97b55c9.
