### ISSUE TITLE
Problem with saving settings after scaninig Wifi network in build 97b55c9

### ISSUE THREAD

**Issue by Pewah** [remne/p1ib#11]
After upgrading to build 97b55c9, all settings disappeared. After clicking the Scan button for Wifi network the "Save Settings" button remained disabled. A workaround was to enter custom SSID and at that time the "Save settings" button was clickable.

**Comment by egeback** [comment]
Another workaround is to inspect the webpage in Chrome and remove the disabled ccs tag.

**Comment by remne** [comment]
Hi,
Sorry for the issue. Its an bug in the p1ib javascript parts during wifiscan in certain conditions. It will be corrected in a firmware during the weekend.
Thanks for reporting the problem.

**Comment by remne** [comment]
Hi,
Fixed in firmware e74c477.

Regards
Andreas
