### ISSUE TITLE
Feature request: composite MQTT messages

### ISSUE THREAD

**Issue by albinsunnanbo** [remne/p1ib#13]
Currently p1ib publishes 1 topic per metric.
It would be nice if there would be an option to get a single topic with a composite JSON document with all metrics instead.
This would simplify some calculations and improve performance for some clients.

**Comment by remne** [comment]
Hi,
Thanks for the request.
I will add this feature in next coming development firmware.

Regards,
Andreas

**Comment by albinsunnanbo** [comment]
Thanks
It would be nice if you could also trim leading zeroes, like in 
![image](https://github.com/remne/p1ib/assets/5158396/497e613f-8bb5-4d44-9a3f-ad48fd42c6ce)
Some libraries are really strict about number formatting

**Comment by remne** [comment]
Json payload for sensors states is nov available in dev firmware (2023-09-14, adcc0f7).
