### ISSUE TITLE
Feature request: admin password

### ISSUE THREAD

**Issue by albinsunnanbo** [remne/p1ib#14]
Option to set admin password during configuration, now the p1ib is free for all on the local network, would be nice with a lockdown for changing settings.

**Comment by remne** [comment]
Hi! 
Latest development firmware contains this feature. 

![image](https://github.com/remne/p1ib/assets/6463341/d76433ff-9a4b-4c0f-99a8-5b0407f99690)


Regards
Andreas

**Comment by remne** [comment]
Login protection is not in the latest stable relase.
