### ISSUE TITLE
HA Entities Warning

### ISSUE THREAD

**Issue by dustrat** [remne/p1ib#17]
Hello!

I recently saw this warning popup i Home Assistant:
![image](https://github.com/remne/p1ib/assets/86410391/e1de84d8-df40-4df6-b2ba-d16268e244e8)

Anything I can do in HA to fix this or is a firmware fix required?

/P

**Comment by remne** [comment]
Hi!

I have create a development firmware that alignes sensor names to HA's new naming conventions (removed p1ib from the name).
However, its just a warning in HA. It can be ignored if one dont want to run a development (test) firmware until it is set as stable (or bugs identified and fixed).

BR,
Andreas

**Comment by dustrat** [comment]
Alright, good to know.
