### ISSUE TITLE
Non decimal in current

### ISSUE THREAD

**Issue by JelpirT** [remne/p1ib#18]
I got no decimals in current flow? any ide how to get it?
![image](https://github.com/remne/p1ib/assets/100702927/42def307-2004-4649-9116-afa89ca5ae11)

**Comment by remne** [comment]
Hi,
What power meter do you have?
I'm not familiar with that model.

To help out to understand why p1ib decodes the information without decimals I need a sample payload. You can get it by activating the remote debug or hooking up the p1ib to usb and connecting to the serial port with a terminal program (2'000'000 baud rate)

Regards,
Andreas

**Comment by JelpirT** [comment]
Hej, jag har denna mätare, vet ej vilken ip debug ska aktiveras till?Skickat från min Galaxy
-------- Originalmeddelande --------Från: Andreas Remnehed ***@***.***> Datum: 2023-09-14  22:51  (GMT+01:00) Till: remne/p1ib ***@***.***> Kopia: JelpirT ***@***.***>, Author ***@***.***> Ämne: Re: [remne/p1ib] Non decimal in current (Issue #18) 
Hi,
What power meter do you have?
I'm not familiar with that model.
To help out to understand why p1ib decodes the information without decimals I need a sample payload. You can get it by activating the remote debug or hooking up the p1ib to usb and connecting to the serial port with a terminal program (2'000'000 baud rate)
Regards,
Andreas

**Comment by JelpirT** [comment]
Edit the answer

**Comment by remne** [comment]
hi, please contact hello @ remne . tech instead via email!
