### ISSUE TITLE
MQTT Topic Prefix not working on development version b896624

### ISSUE THREAD

**Issue by rikardwissing** [remne/p1ib#19]
Found a small issue on development version `b896624`.

Data is still published without the MQTT Topic Prefix even when it is set.

The homeassistant auto discovery data still indicates that it should be published on `mqtttopicprefix/p1ib/...` but it is actually published on `p1ib/...`

<img width="529" alt="image" src="https://github.com/remne/p1ib/assets/22580571/aea19384-4c8d-480b-9fc4-defdaaa61ed5">

<img width="437" alt="image" src="https://github.com/remne/p1ib/assets/22580571/e18e0a7f-e304-41f9-9e91-403b0400595a">

<img width="527" alt="image" src="https://github.com/remne/p1ib/assets/22580571/15ac9358-7c3f-4b8a-ab5d-915c639f6c9a">

**Comment by remne** [comment]
Hi,
Thanks for noticing!

Fixed in latest dev firmware (2023-09-14, adcc0f7).

Regards,
Andreas
