### ISSUE TITLE
Active power L1-3 (solar) show power

### ISSUE THREAD

**Issue by Mika-gbg** [remne/p1ib#24]
Hi,

Recently connected the P1ib as I got a new power meter.
I note that Active power L1-3 (solar) show power even though my solar system is not producing due to evening/dark condtions, see picture.
What could be wrong?

Best regards,
Mika
![IMG_0346](https://github.com/remne/p1ib/assets/149713849/0bd1090e-2b6f-478f-b2ae-a45a1a3771a8)

**Comment by remne** [comment]
Hi,
It is nothing wrong. The solar sensors are a combination of export and import. It will be negative and positive values depending on if you are exporting or importing power. Right now it is matching your import, if you compare the values. 
The only thing that might be wrong is the naming with the word 'solar', :).

**Comment by remne** [comment]
The "solar" sensors exists for people that dont want to create a template sensor in Home Assistant for the combination of export and import sensors.

**Comment by Mika-gbg** [comment]
Great! Thank you for the quick reply!
