### ISSUE TITLE
Energy usage differ

### ISSUE THREAD

**Issue by dustrat** [remne/p1ib#3]
Hi!

Energy usage in HA versus Tibber differ about 5 kWh/day, Tibber shows the higher value. Any Idea what can cause that? I'm using the sensor sensor.p1ib_active_energy_import_q1_q4 in the Energy Dashboard.

**Comment by remne** [comment]
Hi,
I dont know how tibber calculates the energy usage, but the values from the p1ib sensors is the ones your power meter sends out. P1ib does not do any own calculations.

BR,
Andreas

**Comment by dustrat** [comment]
Alright, I'll do some digging.

/Patrik
