### ISSUE TITLE
RJ12 cable length - Is it possible to extend?

### ISSUE THREAD

**Issue by 4integration** [remne/p1ib#30]
Hi,

How long is the included cable?
Is it possible to replace the cable e.g. to a 1 m cable? (or 3 m like this https://www.kjell.com/se/produkter/mobilt/fast-telefoni/installation/telekablar/modulkablar/telefonkabel-rj12-till-rj12-3-m-p38406 )

Regards
Joacim

**Comment by remne** [comment]
Hi,
The included cable is 50cm. However, if you order from m.nu they can also provide a 150cm cable (write message in the order).

Regards,
Andreas
