### ISSUE TITLE
P1ib get disconnected in HomeAssistant if I restarrt HA

### ISSUE THREAD

**Issue by 4integration** [remne/p1ib#33]
Hi,

If I restart HomeAssistant the sensors gets "unknown" which I think relates that HA loose the state and p1ib just send homeassistant messages at startup (= if I restart p1ib then it works again)

Any configuration possible to get this smoother?

/ Joacim

**Comment by 4integration** [comment]
Duplicate? https://github.com/remne/p1ib/issues/32

**Comment by remne** [comment]
Yes, duplicated and fixed in latest firmware.
