### ISSUE TITLE
Documentation for firmware programming

### ISSUE THREAD

**Issue by orfeasKalipolitis** [remne/p1ib#36]
Is there perhaps already documentation on how one could go about modifying the firmware of the device?

I mean specifically for the communication to P1, as the user interface seems quite robust to me (I can't see anything I would like to add).

I would really like to contribute to this project, and doing that while working on connecting to a temperamental electricity meter sounds fun to me (I am weird like that).

**Comment by remne** [comment]
Hi,
P1IB is not open source.

Regards,
Andreas
