### ISSUE TITLE
Support Matter over WiFi or Thread?

### ISSUE THREAD

**Issue by TheBarista1** [remne/p1ib#40]
Hi! 
Version 1.3 of Matter now supports Energy management. Is there a possibility to support Matter over Wifi? Or even better, does the hardware have a radio that supports 802.15.4 so Matter over Thread (mesh) is possible? 

https://csa-iot.org/newsroom/matter-1-3-specification-released/ 
GUI examples https://matter-smarthome.de/en/development/matter-1-3-a-deep-dive-into-the-new-features/#h-measure-energy-consumption-with-matter

**Comment by remne** [comment]
Hi,
P1IB does not have a 802.15.4 radio.
However Matter over Wi-Fi might (most likely) be added in the future. I haven't put any time to investigate it really. 
Its for sure interesting feature to add.

Regards,
Andreas / Remnetech
