### ISSUE TITLE
MQTT: Transformer Ratio Constant

### ISSUE THREAD

**Issue by merbanan** [remne/p1ib#46]
The constant does not follow the MQTT message and the values are not scaled by the constant. Either option should be adopted.

**Comment by remne** [comment]
Issue fixed in latest development firmware.

**Comment by merbanan** [comment]
I tried build 602fe98 and there is no json member that has the transformer factor value.

**Comment by merbanan** [comment]
I tested a58dff6 but there is no mqtt p1ib_transformer_ratio_constant in it.

**Comment by merbanan** [comment]
All the values are scaled properly though. It would be nice with it being there but there is no use for it so yeah, maybe call it closed.
