### ISSUE TITLE
Some state values no longer update in MQTT

### ISSUE THREAD

**Issue by bjorne** [remne/p1ib#53]
Hi,

I've been running the device for a while and love it. However, I noticed that in Home Assistant the Energy dashboard would just show zero energy usage. After digging around it seems like the active energy import state is not being properly updated in MQTT. It does show a continuously updated value in the P1IB interface, though. 

The same goes for a few other fields like the momentary voltage. Other values like the momentary power seem to update just fine.

Here is an example:

![image](https://github.com/user-attachments/assets/74a8535f-eec0-4fdd-8f1e-4e95bcea93b4)

In Home assistant it looks like this:

![image](https://github.com/user-attachments/assets/0267e108-008f-45c1-89a4-770b5dc73716)

As you can see, the HA value is ~402 kWh whereas in P1IB it's showing ~1886 kWh, so it's been stuck for a longer time.

The following screenshot from MQTT Explorer shows the values that update continuously highlighted, and most of the ones not highlighted seem stuck:

![image](https://github.com/user-attachments/assets/62473983-9f6b-4dcb-a613-76412ff81078)

I would like to try to factory reset the device, but let me know if you would like more information to troubleshoot this issue before I do.

**Comment by remne** [comment]
Hi,
It looks like you have activated "json state" in your P1IB settings, which probably explains why no messages are sent on the per sensor topics.
![image](https://github.com/user-attachments/assets/c1170e85-ba4b-4be0-a858-e782940f1f3d)

In your image its not visible, but at least the sensor_state topic is there with the json payload.

Regards,
Andreas

**Comment by bjorne** [comment]
Thanks for the suggestion. I should have mentioned I tried to enable this briefly to try and see if there was any difference but the problem seems to exist also in this state, i.e. only some of the properties in the state have a value. The screenshots I shared was from when I had disabled it again (but the topic remains in mqtt, I guess.)

**Comment by bjorne** [comment]
Not sure that my point was clear above. When I enable the feature, the JSON state looks like this:

```json{
  "p1ib_hourly_active_import_q1_q4": "",
  "p1ib_hourly_active_export_q2_q3": "",
  "p1ib_hourly_reactive_import_q1_q2": "",
  "p1ib_hourly_reactive_export_q3_q4": "",
  "p1ib_active_power_plus_q1_q4": "",
  "p1ib_active_power_minus_q2_q3": "",
  "p1ib_reactive_power_plus_q1_q2": "",
  "p1ib_reactive_power_minus_q3_q4": "",
  "p1ib_active_power_plus_l1": "",
  "p1ib_active_power_minus_l1": "",
  "p1ib_active_power_plus_l2": "",
  "p1ib_active_power_minus_l2": "",
  "p1ib_active_power_plus_l3": "",
  "p1ib_active_power_minus_l3": "",
  "p1ib_reactive_power_plus_l1": "",
  "p1ib_reactive_power_minus_l1": "",
  "p1ib_reactive_power_plus_l2": "",
  "p1ib_reactive_power_minus_l2": "",
  "p1ib_reactive_power_plus_l3": "",
  "p1ib_reactive_power_minus_l3": "",
  "p1ib_voltage_l1": "",
  "p1ib_voltage_l2": "",
  "p1ib_voltage_l3": "",
  "p1ib_current_l1": "",
  "p1ib_current_l2": "",
  "p1ib_current_l3": "",
  "p1ib_firmware": "f934567",
  "p1ib_update_available": "",
  "p1ib_import_export_l1": 0.042,
  "p1ib_import_export_l2": 0.196,
  "p1ib_import_export_l3": 0.148,
  "p1ib_import_export": 0.386,
  "p1ib_rssi": "-90",
  "p1ib_meter": "KAM5",
  "p1ib_mac": "b0b21ca2350c",
  "p1ib_clock_date": "2024-09-17T11:18:41Z",
  "p1ib_telegrams_crc_ok": 40,
  "p1ib_ip": "192.168.66.37"
}
```

I assume that all the values should be populated?

The diff between two messages looks something like this (with 3-5 updated values)

![image](https://github.com/user-attachments/assets/2484f0c8-0a26-4c74-a49c-d52c0994d0ac)

Not sure if this helps narrow it down, but to me it seems to suggest that the reported state is missing some values regardless of whether the JSON state is being used or not?

**Comment by bjorne** [comment]
I went ahead and did a factory reset. Reconfigured the same MQTT settings and it is now updating all values as expected. Feel free to close this unless you want to investigate it further.

**Comment by remne** [comment]
Its strange indeed. I'm not sure how this error could occur. I've tried to reproduce the problem, but wasn't successful. 
Will close the ticket for now, lets see if it pops up again.
