### ISSUE TITLE
MQTT state does not update 

### ISSUE THREAD

**Issue by MagnusPer** [remne/p1ib#54]
Today I got my new P1IB, great product! My use-case is to get current measurements via MQTT but the states does not updates as shown in local dashboard. Looking in number of messages in MQTT explorer shows no updates!

Firmware version: Build 54aa555

![image](https://github.com/user-attachments/assets/5ab3637c-67e9-436b-ade8-52687d712edf)

**Comment by MagnusPer** [comment]
After some reading in closed issues I found this one https://github.com/remne/p1ib/issues/53 which lead me to do a factory reset. Since then it works perfectly 

![image](https://github.com/user-attachments/assets/9c5da8f0-aefb-469e-b8fa-8c7e467fadc8)

**Comment by remne** [comment]
Hi, 
Thanks for reporting this issue. 
I need to dig deeper into this, as you are the second user in a relative short time that have experienced this.

Regards,
Andreas

**Comment by remne** [comment]
I think you might have enabled "reduced mode", which in your firmware version sends the clock_date and the calculated power metrics, but not the other ones.

This was the case with the other customer as well.
I will close the ticket, but if you see this issue again in the future, please reopen the issue.

**Comment by bjorne** [comment]
I just wanted to clarify that reduced data mode was not the issue in #53 - and doesn't seem to apply here either? It looks to me like we hit the same problem where some state stopped updating without explanation and the only known fix is a factory reset.

**Comment by remne** [comment]
It is the reduced mode. 
But I still dont know why it was activated (even if the webui didnt show it as enabled or not).
