### ISSUE TITLE
Entites (solar) in Home Assistant.

### ISSUE THREAD

**Issue by Newman820** [remne/p1ib#55]
Entites present as "P1IB Active power L1 (solar)", "P1IB Active power L2 (solar)" and "P1IB Active power L3 (solar)" in Home Assistant represents import from grid and should not have "(solar)" in its name.

If "solar" should be preset it should be on "P1IB Active power minus L1", "P1IB Active power minus L2" and "P1IB Active power minus L1" which represent export to grid.

<img width="1024" alt="Skärmavbild 2024-10-25 kl  18 55 20" src="https://github.com/user-attachments/assets/44888e7a-1961-4d0b-bcd1-0ead3a5cc381">

**Comment by remne** [comment]
The 'solar' part of the name is already removed in latest dev firmware that will be pushed in the coming days.

But it will not be added to the power minus sensors.
