### ISSUE TITLE
MQTT rate limit not working

### ISSUE THREAD

**Issue by bjorne** [remne/p1ib#59]
Thank you for adding the rate limit feature. I think the way you have implemented it will be very useful for me.

I haven't been able to make it work, though, it keeps posting to MQTT every second.

I have tried three different values: 10, 20, and 30 (with save+restarts in between of course.)

![image](https://github.com/user-attachments/assets/4302b957-d8c8-4411-9c03-f7bc69cf73ba)

I have also verified that the config actually contains the value I have set by inspecting the network response for `getConfig` from the browser when loading the Dashboard:

![image](https://github.com/user-attachments/assets/c5e9e6ff-9382-4953-b78f-ac7d6e5891e5)

**Comment by remne** [comment]
I had at as a sub-option under reduced mode first, but changed my mind in the last minute and moved it as a generic option for mqtt and I missed to remove a condition that rm had to be enabled.
I've corrected it in the latest dev firmware (5e4898f).

**Comment by bjorne** [comment]
With 5e4898f it works as expected, thanks again for the addition!
