### ISSUE TITLE
Feature request: Ability to connect to unlisted WiFi SSID

### ISSUE THREAD

**Issue by exxoff** [remne/p1ib#7]
I miss an option to connect to a hidden SSID since my IoT network isn't broadcasting its SSID.

**Comment by remne** [comment]
Hi,
I added support for custom/hidden SSID in latest development firmware if you want to try it out.

Let me know how it goes.

BR,
Andreas

**Comment by exxoff** [comment]
Hi!

It works well, it connected to my hidden network.

 / Per
